### ISSUE TITLE
Warning TypeScript import images

### ISSUE THREAD

**Issue by LanHuong142002** [GraphicDThanh/huong-le-nguyen-lan-internship#275]
- When I import images the warning of TypeScript gonna be like this
![a](https://user-images.githubusercontent.com/93907879/216953591-11a23cdc-0836-44b6-95ff-03ca32a96a62.png)

- I try to add the file custom.d.ts to the config following the guide but it does not work. Here is my custom.d.ts
```
// custom.d.ts

declare module '*.svg' {
  import * as React from 'react';

  const content: React.FunctionComponent<React.SVGAttributes<SVGElement>>;

  export default content;
}
```

```
// tsconfig.json

...
"include": ["*/.ts", "*/.tsx", "src/custom.d.ts"]
...
```
- And if I add `"src"` to include, the warning in `import star from '../../assets/star.svg';` gonna disappear
```
// tsconfig.json

...
"include": ["*/.ts", "*/.tsx", "src/custom.d.ts", "src"]
...
```
- But it makes `import React from 'react';` have warning `'React' is declared but its value is never read.`
![a](https://user-images.githubusercontent.com/93907879/217507149-a06579d5-8e05-43ca-9356-a7f9313e04ec.png)
- and also have a new error in src
![a](https://user-images.githubusercontent.com/93907879/217505125-4341d1c3-b356-46b6-8a25-5553ae16a3c6.png)

- Guides:
  - https://stackoverflow.com/questions/44717164/unable-to-import-svg-files-in-typescript
  - https://annacoding.com/article/5I7om6mCrW25KeA4ObeyMJ/Two-ways-to-solve:-Cannot-find-SVG-module-error-when-compiling-Typescript-in-React-application 
  - https://dev.to/minompi/add-images-to-a-react-project-with-typescript-4gbm
  - https://www.carlrippon.com/using-images-react-typescript-with-webpack5/

**Comment by kietnguyen-agilityio** [comment]
- Since React 17, you don't need to import React in jsx anymore, let just remove them. Refer: https://reactjs.org/blog/2020/09/22/introducing-the-new-jsx-transform.html
- You only need "custom.d.ts" instead of "src/custom.d.ts" but since you are using **vite**, which already declare module for [svg](https://github.com/vitejs/vite/blob/main/packages/vite/client.d.ts#L129), you don't need to declare it. You just need `"include": ["src"],`, so it will use declared module in **vite**

Let me know if this works for you

**Comment by LanHuong142002** [comment]
- Follow your comments:
  - I removed `import React from 'react';` and removed file `custom.d.ts`
  - And add `"src"` in include on tsconfig file like this
`"include": ["*/.ts", "*/.tsx", "src"],`

And it's work! Thanks for your help.
